server:
  port: 8080
  contextPath: /MiracleMessenger
---
spring:
  profiles: local,default
datasource:
  messenger:
    url: jdbc:mysql://localhost:3306/Messenger
    username: springuser
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: create
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

